# Generated by Django 3.0.3 on 2020-03-09 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=128)),
                ('general_rent_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('second_name', models.CharField(blank=True, default='', max_length=128)),
                ('dateOfBirth', models.DateTimeField()),
                ('rent_time', models.DateTimeField()),
                ('auto', models.ManyToManyField(to='rent_cars.Auto')),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_cars.Brand'),
        ),
    ]
