# Generated by Django 3.0.3 on 2020-03-14 17:24
# Custom migration for sanity ranks

from django.db import migrations
from insane_app.models import SanityRank


def create_sanity_ranks(apps, schema_editor):
    SanityRank.objects.get_or_create(name='noobie', sanity_cap=12)
    SanityRank.objects.get_or_create(name='adept', sanity_cap=25)
    SanityRank.objects.get_or_create(name='madman', sanity_cap=50)
    SanityRank.objects.get_or_create(name='insanion', sanity_cap=100)


class Migration(migrations.Migration):

    dependencies = [
        ('insane_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sanity_ranks)
    ]
