# Generated by Django 3.0.3 on 2020-03-28 16:29

from django.db import migrations, models
import insane_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('insane_app', '0002_auto_20200318_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='src',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default="'insane_app/images/default.jpg", upload_to=insane_app.models.get_image_path),
            preserve_default=False,
        ),
    ]
