# Generated by Django 3.0.3 on 2020-04-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insane_app', '0003_auto_20200328_1829'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('image', 'product')},
        ),
    ]
